### ISSUE TITLE
how do you think the core ML framework with WWDC 2017

### ISSUE THREAD

**Issue by minipeach** [hollance/Forge#11]
i think a lot of apps that use core ML will come to App Store :)
and Metal 2 is only for Mac OS ?

**Comment by hollance** [comment]
CoreML makes most of Forge obsolete. 😉

**Comment by minipeach** [comment]
Core ML is highly integration ,  Forge is flexible  :)

**Comment by gwangsc** [comment]
@hollance not really. 
I like Forge better than CoreML. CoreML is hard to debug as a block box. And it is hard to customize with preprocessing and postprocessing. 
Please keep your amazing working going!

**Comment by hollance** [comment]
@gwangsc Thanks. :-) However, MPS now has a graph API, which does pretty much the same thing as Forge. Currently Forge no longer even works on iOS 11, and it's going to be tricky to keep it backwards compatible with iOS 10. Anyway, we'll see how it works out. ;-)

**Comment by gwangsc** [comment]
With dilated conv and deconv layers supported in MPSCNN in iOS 11, Forge can do even more. And to run a model on devices with iOS 10 and older, Forge is the way to go.

**Comment by steve21124** [comment]
will it possible to convert YOLO9000 model to CoreML and use it with CoreML? sorry if it is too basic question. Since I just start to learn all the lingos

**Comment by hollance** [comment]
@steve21124 I've only converted Tiny YOLO so far, not the full one. (The full YOLO9000 will be too slow to run on mobile anyway, unless you want to run it on static photos.)
