### ISSUE TITLE
Use Forge with deployment target < 10.3

### ISSUE THREAD

**Issue by Aiwis** [hollance/Forge#12]
Hi,

I'm trying to add Forge to my app (deployment target = 9.0). 

I get this compiling error : 

> YOLO.swift:2:8: Module file's minimum deployment target is ios10.3 v10.3: Forge.framework/Modules/Forge.swiftmodule/arm64.swiftmodule

I've tried to set the Framework as Optional and to do the last part of [this page](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WeakLinking.html#//apple_ref/doc/uid/20002378-107262) but I still get the same error.

I can't change the target of my app.

Any help would be appreciated :)

**Comment by hollance** [comment]
You can't use Forge with iOS 9. The Metal Performance Shaders used only work on iOS 10 and up.

**Comment by Aiwis** [comment]
Thank you for your answer, I know that I can't use Forge with iOS 9 but I wanted to handle the backwards compatibility by checking the version with something like "if available". 

I'll try to generate the framework with a lower target version.
