### ISSUE TITLE
ETC_BAD_ACCESS code = 10

### ISSUE THREAD

**Issue by jordanhart** [hollance/Forge#14]
Hi!

I wrote my own CNN in the YOLO demo (currently trying to replicate squeezeDet). I changed the model layers in the init and have my weights converted as .bin files in the parameters folder. The only other item changed was labels. When I run I get "ETC_BAD_ACCESS code = 10" on the flags line of 
"conv = MPSCNNConvolution(device: device,
                             convolutionDescriptor: desc,
                             kernelWeights: weights.pointer,
                             biasTerms: biases?.pointer,
                             flags: .none)" 

Photo included below. What could be the issue causing this? Any advice on solving?

Thank you so much!

![screen shot 2017-06-20 at 2 33 44 pm](https://user-images.githubusercontent.com/10838221/27357155-f695cd6a-55c5-11e7-888a-22e83f6c92f3.png)
![screen shot 2017-06-20 at 5 39 49 pm](https://user-images.githubusercontent.com/10838221/27361932-81d44104-55df-11e7-945d-86f08a2a9b9e.png)

Edit: My problem is from this line     
let output = fire11Result --> Convolution(kernel: (3, 3), channels: 72, stride: (1,1), activation: nil, name: "conv12") //error is caused by this line

The app runs using fire11Result, the second to last layer, as the output. 

Any idea?

Thank you!

**Comment by jordanhart** [comment]
![screen shot 2017-06-20 at 9 12 41 am](https://user-images.githubusercontent.com/10838221/27343742-b2de0826-5598-11e7-85ac-4387473c7762.png)
![screen shot 2017-06-20 at 9 12 25 am](https://user-images.githubusercontent.com/10838221/27343741-b2dcf1b6-5598-11e7-85a4-f03f622e5cc7.png)

**Comment by hollance** [comment]
That sounds like your weights / biases file do not have enough values in them.

**Comment by jordanhart** [comment]
Thank you so much for helping!

Turns out put the wrong number for the kernel.

**Comment by jordanhart** [comment]
Also, just for helping other beginners, uploading the weights conversion script I put together for converting a frozen .pb tensor flow model to Forge (did not use fully connected layers but include link where could copy paste that part in). 
[Frozen_tensorflow_model_to_mpscnn.py.zip](https://github.com/hollance/Forge/files/1096162/Frozen_tensorflow_model_to_mpscnn.py.zip)
