### ISSUE TITLE
A issues about memory leak

### ISSUE THREAD

**Issue by gxl2024595** [hollance/Forge#21]
i add a viewcontroller which as the first vc in MobileNetsDemo.Then present the cameracontroller in demo ,and then dismiss the cameracontroller  .But i find that when i do this ,there is about 10M memory is not released.And everytime i present the cameracontroller ,there is more 10M in memory which is not released. i guess the issues is everytime createNeuralNetwork the memory will in increase，but i cannot solve the problem.How could i solve this problem??

**Comment by hollance** [comment]
You can use Instruments with the Allocations instrument to find out exactly where that extra 10MB comes from.

**Comment by gxl2024595** [comment]
I had use Instruments to find out where that 10MB ,but i finally cannot find it .I had some screenshots.
<img width="1019" alt="01455bde-944c-4b66-8c8d-a800c55aff6a" src="https://user-images.githubusercontent.com/16165921/30606953-001f0d88-9da6-11e7-8cf2-9cba299c5d49.png">

**Comment by gxl2024595** [comment]
<img width="1282" alt="a832ad3c-37f4-43be-8df1-c5f83736d606" src="https://user-images.githubusercontent.com/16165921/30606999-3533fcd6-9da6-11e7-8406-b018424b72a1.png">

**Comment by gxl2024595** [comment]
<img width="260" alt="374227cf-cbf9-476b-bcf4-0859f1a87173" src="https://user-images.githubusercontent.com/16165921/30607024-4d435812-9da6-11e7-8d75-f8cc2111284c.png">

**Comment by gxl2024595** [comment]
when call this function ,the memory will increase,and when i dismiss the cameracontroller ,the extra 10MB would not be released
<img width="652" alt="7818a0b0-6182-463c-8adb-8d8f88a1a501" src="https://user-images.githubusercontent.com/16165921/30607193-bf803094-9da6-11e7-93ea-528ac437f4bb.png">
Could you try to add a viewcontroller in your demo(MobileNets) ,and you can present the cameratroller and dismiss  the cameratroller for sereval times.You will find the same issues.Please help me Great God^^

**Comment by hollance** [comment]
It's definitely not a good idea to create the neural network every time. Just create it once and keep re-using it.

**Comment by gxl2024595** [comment]
But,if i want to swich the training model ,i have to create the neural network again.Is there any way to swich the training model without creating  the neural network again？

**Comment by hollance** [comment]
At this point, no. There is no way to change the weights after you've created the model. So in that case you do have to create the neural network again.

**Comment by gxl2024595** [comment]
Ok, i get it.Thanks.

**Comment by hollance** [comment]
@gxl2024595 I fixed the memory leak. Give it a try and see if it works for you.

**Comment by gxl2024595** [comment]
Thank you,the memory leak is fixed.Thank you for your help！！
