### ISSUE TITLE
Do you have any plan to implement ResNet with Forge?

### ISSUE THREAD

**Issue by minhohihi** [hollance/Forge#25]
First of all, your Forge make me happy. Thank you.
Now, I'm trying to implement ResNet using MPS, but stuck at adding two conv layers.
Is there any MPS API to support ResNet or do I have to copy two weights of conv layers from GPU to CPU and pushing again to GPU after calculating 'ADD'? (I think the latter is bad idea).  I'm glad if you give me a little hint.

thank you.

**Comment by hollance** [comment]
You should be able to use an MPS kernel for adding two images together, but Forge does not support this currently. You might want to try using the MPS "node" API instead of Forge, although that is iOS 11+ only.
