### ISSUE TITLE
Are you going to develop Deconvolution layers?)

### ISSUE THREAD

**Issue by mrlzla** [hollance/Forge#26]
Hi! Amazing framework! Thanks! The framework would be even more amazing if you provide convolution transpose layer ;))) Are you going to do this? :)

**Comment by hollance** [comment]
Good question. :-) MPSCNN has some new layer types that I should add to Forge, including transposed convolution. But no promises. ;-)

**Comment by cscyangj** [comment]
Looking Forward...
