### ISSUE TITLE
How to implement element wise layer in forge

### ISSUE THREAD

**Issue by qkxiaohuang** [hollance/Forge#28]
Hi, I want to convert a caffemodel which includes the elementwise(sum operation) layer, however,  there is no implementation in forge, so I want to write it by myself. How to implement this layer as soon as possible? Please help me, thanks!

**Comment by hollance** [comment]
In Layers.swift, add a new subclass for the layer. Check out the Conv class for how to do this (although you don't need any weights, I suppose). Use the elementwise addition kernel from MPS. It should only be a few lines of code.

**Comment by qxin** [comment]
Hi..sorry, same question, element wise layer is important  (needed by mobileNet v2, resnet...etc
