### ISSUE TITLE
Forge is not support ios 11.3

### ISSUE THREAD

**Issue by gxl2024595** [hollance/Forge#33]
I update my xcode and iphone to ios11.3. Then the Forge can not build success.You maybe update the forge to support ios11.3,because some class have made some changes in ios 11.3

**Comment by hollance** [comment]
Yes, I am aware of this and I have a fix for it but have not added this into Forge yet.

**Comment by gxl2024595** [comment]
Great,and when you would add this?

**Comment by hollance** [comment]
OK, fixed. :-)

**Comment by gxl2024595** [comment]
You know,you are handsome!!
