### ISSUE TITLE
Update ios version and xcode version, can not run any more.

### ISSUE THREAD

**Issue by Shelro** [hollance/Forge#36]
Hi, I just update my ios version to 11.3, my bad! 
So I also update xcode to match my iphone, and I got some error like: "Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1".

And I also got some error in Layer.swift:"Type of expression is ambiguous without more context"
or "'MPSRectNoClip' is only available on iOS 11.0 or newer".

Could you please help me to fix this problem?
Thank you!

**Comment by Shelro** [comment]
<img width="695" alt="2018-04-21 2 47 47" src="https://user-images.githubusercontent.com/17904714/39081452-1ab6e604-4574-11e8-8ae8-ce8373a26af5.png">

A screenshot of one error.

**Comment by hollance** [comment]
I don't know about that first error (do a clean build?) but the others have been fixed so if you pull in the latest changes that should work again.

**Comment by Shelro** [comment]
Thank you. I already fix this problem.
