### ISSUE TITLE
Custom TinyYOLO doesn't work

### ISSUE THREAD

**Issue by MatinC** [hollance/Forge#37]
I have been trying to use Forge to detect a custom object based on TinyYolo model. By the way, every time I tried to run it gave me this error. My custom model consists of 2 classes, and tried to changes several parameters and seems not to work

![untitled](https://user-images.githubusercontent.com/32949185/39161205-cf183072-4799-11e8-9a4f-16b4dce57d01.jpeg)

The TinyYolo which based on voc that came with your example works fine.

**Comment by hollance** [comment]
It looks like your output array has more or fewer than 7*13*13 numbers in it.

**Comment by MatinC** [comment]
I've change it to 35 and it worked
Thanks you
