### ISSUE TITLE
update to Xcode 9.4

### ISSUE THREAD

**Issue by suolemon** [hollance/Forge#38]
Hi,There are two problems come up when update to Xcode 9.4.
**Layers.swift** has one error :_Type of expression is ambiguous without more context_ 
```
conv = MPSCNNConvolution(device: device,
                             convolutionDescriptor: desc,
                             kernelWeights: weights.pointer,
                             biasTerms: biases?.pointer,
                             flags: .none)
```
and in file **LayerHelpers.swift** has the same error in the following line.
```
  let layer = MPSCNNConvolution(device: device,
                                convolutionDescriptor: desc,
                                kernelWeights: weightsData.pointer,
                                biasTerms: biasData?.pointer,
                                flags: .none)
```

**Comment by hollance** [comment]
Are you using the latest version of Forge? (Note that this project is no longer being supported by me.)

**Comment by suolemon** [comment]
Yes,I’m using the latest version of Forge in my project. And I run Forge in Xcode 9.4 there was no error occurred.But in my project ,it still showing errors about ‘ MPSCNNConvolution’ as 'Type of expression is ambiguous without more context'.
Thanks.

**Comment by hollance** [comment]
You need to add the bridging header to your project as well as the header it includes.
