### ISSUE TITLE
[question] TensorFlow Lite

### ISSUE THREAD

**Issue by y-ich** [hollance/Forge#45]
Hi, @hollance san,

Have you ever evaluate TensorFlow Lite on iOS/iPadOS for GPU(I mean not for Neural Engine)?

As you had pointed out at some article, Core ML is slower than MPSCNN.
So I expected Metal delegate of TensorFlow Lite and tried but am disappointed it’s performance.
If you have some insights, could you tell me some?

Thanks.

**Comment by hollance** [comment]
I haven't really used TFLite very much, so I couldn't say. I also think Core ML is the go-to choice these days, I would only try MPSCNN if there was a _really_ good reason for it.

**Comment by y-ich** [comment]
Thank you for your comment!

I know what you meant in some article, but also it is true even today.
Core ML on GPU is twice or more slower than OpenCL implementation on macOS in another case I tried.

I want to get best performance on both ANE and GPU and expected it from TensorFlow Lite but…

Anyway thank you!
Please take care of yourself in COVID-19 period.

**Comment by hollance** [comment]
Note that TF Lite's ANE support actually runs the model on Core ML. For Metal they use their own GPU kernels, plus maybe some MPSCNN (it's been a while since I checked).

**Comment by y-ich** [comment]
Sure, so I had expected GPU boost by TF Lite since Core ML on GPU is slow while it keeps speed in the case which ANE is available.

Thank you for your comment.
