### ISSUE TITLE
Building own app causes Libmobilegestalt issue

### ISSUE THREAD

**Issue by ankghost0912** [hollance/Forge#5]
Hi, 

I had to make this a new issue since it's unrelated to the previous one. I've built my app using Forge's DSL and converted the collective weights into layer by layer weights. The app builds correctly but when I try to run it, I encounter the following issue: 

`libMobileGestalt MobileGestaltSupport.m:153: pid 10398 (Labels) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled `

I've tried to track down the bug, but I can't seem to locate it. My development environment is xcode 8.3 and iOS 10.3.  Any pointers would be appreciated in this direction

**Comment by minipeach** [comment]
https://forums.developer.apple.com/thread/72286

**Comment by hollance** [comment]
Yeah, I don't know why this happens. Except for this warning it doesn't seem to cause any problems, though.
