### ISSUE TITLE
Unable to archive the app with Forge.

### ISSUE THREAD

**Issue by Shoshin23** [hollance/Forge#9]
Hey! 

Awesome framework, really like using it. But here's a big issue. I'm unable to archive the app because it throws a whole bunch of unresolved error issues. The app works great during development but I'm unable to archive the app. :) 

Attaching a pic for you.

Do let me know how to fix this. 

Thanks!

![archive_fail](https://cloud.githubusercontent.com/assets/2094133/26454382/91b06432-4184-11e7-9eb3-9747397b6f95.jpg)

**Comment by Shoshin23** [comment]
Right. There is an issue with my release build. I'm not sure if I'm missing something here or not linking it correctly. I followed the installation instructions on your Readme page. Any help would be greatly appreciated.

**Comment by Shoshin23** [comment]
Right. I was able to fix this. Just logging in to write and close this issue. 
Looks like Forge is currently compatible with only arm64 architecture whereas the apps that Xcode instantiated by default was also including armv7 and armv7s. 

I'm guessing because of certain limitations in older models(armv7, I guess) Forge only currently runs on this single architecture. Would like to know if my assumption is right @hollance.

Closing this issue for but will reopen in case of fresh trouble. 👍

**Comment by Shoshin23** [comment]
Okay. I did face another issue while building the app with Forge. 

Dear developer,

We have discovered one or more issues with your recent delivery for "InceptionApp". To process your delivery, the following issues must be corrected:

Unexpected CFBundleExecutable Key - The bundle at '/Payload/InceptionApp.app/Forge/Forge/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team

**Comment by hollance** [comment]
The first error is indeed because Forge only gets compiled for arm64.

The second error sounds like an issue with your app bundle. I haven't tried submitting an app made with Forge to the App Store yet, but I don't see an obvious problems with the way the Forge framework is set up. How did you create that InceptionApp? By including Forge.framework into your app?

**Comment by Shoshin23** [comment]
Hey! 
I followed the exact same instructions in the README. I included Forge.xcodeproj and the Forge.framework under Forge.xcodeproj in the embedded binaries. 

Do let me know if you need an update on anything else related to it.

**Comment by hollance** [comment]
Have you tried doing what the message says and removed the CFBundleExecutable key from Forge's Info.plist?
